//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Attack_notice_prefab
    {
        public const string BundleName = "attack notice_prefab";
        public const string ATTACK_NOTICE = "attack notice";
    }
    public class Battlefield_air_wall_mat
    {
        public const string BundleName = "battlefield air wall_mat";
        public const string BATTLEFIELD_AIR_WALL_MAT = "battlefield air wall mat";
    }
    public class Beam_prefab
    {
        public const string BundleName = "beam_prefab";
        public const string BEAM = "beam";
    }
    public class Bigork_prefab
    {
        public const string BundleName = "bigork_prefab";
        public const string BIG_ORK = "big ork";
        public const string BIGORK = "bigork";
    }
    public class Boss_room_1_ogg
    {
        public const string BundleName = "boss room 1_ogg";
        public const string BOSS_ROOM_1 = "boss room 1";
    }
    public class Boss_room_2_ogg
    {
        public const string BundleName = "boss room 2_ogg";
        public const string BOSS_ROOM_2 = "boss room 2";
    }
    public class Boss_room_3_ogg
    {
        public const string BundleName = "boss room 3_ogg";
        public const string BOSS_ROOM_3 = "boss room 3";
    }
    public class Chief_prefab
    {
        public const string BundleName = "chief_prefab";
        public const string CHIEF = "chief";
    }
    public class Dark_elf_prefab
    {
        public const string BundleName = "dark elf_prefab";
        public const string DARK_ELF = "dark elf";
    }
    public class Defence_prefab
    {
        public const string BundleName = "defence_prefab";
        public const string DEFENCE = "defence";
    }
    public class Entrance_move_ogg
    {
        public const string BundleName = "entrance move_ogg";
        public const string ENTRANCE_MOVE = "entrance move";
    }
    public class Fireball_prefab
    {
        public const string BundleName = "fireball_prefab";
        public const string ENEMY_FIREBALL = "enemy fireball";
        public const string PLAYER_FIREBALL = "player fireball";
    }
    public class Full_friction_physicmaterial
    {
        public const string BundleName = "full friction_physicmaterial";
        public const string FULL_FRICTION = "full friction";
    }
    public class Gamestarttimeline_playable
    {
        public const string BundleName = "gamestarttimeline_playable";
        public const string GAMESTARTTIMELINE = "gamestarttimeline";
    }
    public class Hit_prefab
    {
        public const string BundleName = "hit_prefab";
        public const string HIT = "hit";
    }
    public class Janissary_prefab
    {
        public const string BundleName = "janissary_prefab";
        public const string JANISSARY = "janissary";
    }
    public class Main_theme_ogg
    {
        public const string BundleName = "main theme_ogg";
        public const string MAIN_THEME = "main theme";
    }
    public class Postprocessingprofile_asset
    {
        public const string BundleName = "postprocessingprofile_asset";
        public const string POSTPROCESSINGPROFILE = "postprocessingprofile";
    }
    public class Red_demon_prefab
    {
        public const string BundleName = "red demon_prefab";
        public const string RED_DEMON = "red demon";
    }
    public class Return2mainmenutimeline_playable
    {
        public const string BundleName = "return2mainmenutimeline_playable";
        public const string RETURN2MAINMENUTIMELINE = "return2mainmenutimeline";
    }
    public class Rock_shoot_prefab
    {
        public const string BundleName = "rock shoot_prefab";
        public const string ROCK_SHOOT = "rock shoot";
    }
    public class Shaman_prefab
    {
        public const string BundleName = "shaman_prefab";
        public const string SHAMAN = "shaman";
    }
    public class Shieldbreak_attack_notice_prefab
    {
        public const string BundleName = "shieldbreak attack notice_prefab";
        public const string SHIELD_BREAK_ATTACK_NOTICE = "shield break attack notice";
    }
    public class Skeleton_prefab
    {
        public const string BundleName = "skeleton_prefab";
        public const string SKELETON = "skeleton";
    }
    public class Statue_normal_attack_prefab
    {
        public const string BundleName = "statue normal attack_prefab";
        public const string STATUE_NORMAL_ATTACK = "statue normal attack";
    }
    public class Statue_shieldbreak_attack_prefab
    {
        public const string BundleName = "statue shieldbreak attack_prefab";
        public const string STATUE_SHIELD_BREAK_ATTACK = "statue shield break attack";
    }
    public class Sub_theme_ogg
    {
        public const string BundleName = "sub theme_ogg";
        public const string SUB_THEME = "sub theme";
    }
    public class Uidialoguepanel_prefab
    {
        public const string BundleName = "uidialoguepanel_prefab";
        public const string UIDIALOGUEPANEL = "uidialoguepanel";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "uihomepanel";
    }
    public class Uinoticepanel_prefab
    {
        public const string BundleName = "uinoticepanel_prefab";
        public const string UINOTICEPANEL = "uinoticepanel";
    }
    public class Uiscenenamepanel_prefab
    {
        public const string BundleName = "uiscenenamepanel_prefab";
        public const string UISCENENAMEPANEL = "uiscenenamepanel";
    }
    public class Undead_knight_prefab
    {
        public const string BundleName = "undead knight_prefab";
        public const string UNDEAD_KNIGHT = "undead knight";
    }
    public class Warning_prefab
    {
        public const string BundleName = "warning_prefab";
        public const string WARNING = "warning";
    }
    public class Warrior_prefab
    {
        public const string BundleName = "warrior_prefab";
        public const string WARRIOR = "warrior";
    }
    public class Zero_friction_physicmaterial
    {
        public const string BundleName = "zero friction_physicmaterial";
        public const string ZERO_FRICTION = "zero friction";
    }
}
